force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Owner Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Company Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Convertible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RentalManagement.cls
public with sharing class RentalManagement {

    @AuraEnabled
    public static List<Car__c> getAllCars() {
        List<Car__c> cars = [
            SELECT  Id, Name, Account__r.Name, Price__c, Picture__c
            FROM    Car__c
        ];
        return cars;
    }

    @AuraEnabled
    public static List<Car__c> getAvailableCars(String carType, Integer minPrice, Integer maxPrice) {
        List<Car__c> cars = [
            SELECT  Id, Name, Account__r.Name, Price__c, Picture__c
            FROM    Car__c
            WHERE   Type__c = :carType
            AND     Price__c >= :minPrice
            AND     Price__c <= :maxPrice
        ];
        return cars;
    }

}